version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MCP_PLAYWRIGHT_COMMAND=npx
      - MCP_PLAYWRIGHT_ARGS=@playwright/mcp@latest
      - DEBUG=1
      - DRY_RUN=0
      - OPENAI_API_KEY=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
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_MODEL=gpt-4o-mini
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
